version: "3.9"
services:
  backend:
    build:
      context: ./be
    container_name: backend
    restart: always
    ports:
      - 3001:3001

  frontend:
    build:
      context: ./fe
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
