export enum MenuItems {
  DASHBOARD = 'dashboard',
  USERS = 'users',
  PLAN_DRAFT = 'plan-draft',
  PRODUCTS = 'products',
  CUSTOMERS = 'customers',
  ID_BROWSER = 'id-browser',
  ADHOC = 'adhoc',
  INTELLIGENCES = 'intelligences',
  SAMPLES = 'samples',
  REGIONS = 'regions',
  PROMOTERS = 'promoters',
  LEAVE_MANAGEMENT = 'leave-management',
  CUSTOMER_SERVICE = 'customer-service',
  NOTIFICATIONS = 'notifications',
  EVALUATIONS = 'evaluations',
  EMAIL = 'email',
}
